In [2]:
import pandas as pd
import numpy as np

from pathlib import Path

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 20)

In [5]:
# Load CPU Datasets
cpu1 = pd.read_csv(
    r"C:\Users\Avilasha\Desktop\CPU_Predictive_Maintenance\data\Raw\DataCenter Last month data\SERVER WISE DATA\CPU DATA\superadmin-cpu-custom (1).csv"
)

cpu2 = pd.read_csv(
    r"C:\Users\Avilasha\Desktop\CPU_Predictive_Maintenance\data\Raw\DataCenter Last month data\SERVER WISE DATA\CPU DATA\superadmin-cpu-custom (2).csv"
)

cpu3 = pd.read_csv(
    r"C:\Users\Avilasha\Desktop\CPU_Predictive_Maintenance\data\Raw\DataCenter Last month data\SERVER WISE DATA\CPU DATA\superadmin-cpu-custom.csv"
)

In [6]:
# inspect CPU Datasets
print("CPU1")
display(cpu1.head())

print("CPU2")
display(cpu2.head())

print("CPU3")
display(cpu3.head())

CPU1

   hostId                 timestamp     hostName  cpuUsagePct   status
0       1  2026-06-10T06:20:04.701Z  10.10.10.65         4.07  Warning
1       1  2026-06-10T06:15:15.846Z  10.10.10.65         3.88  Warning
2       1  2026-06-10T06:11:04.920Z  10.10.10.65         3.78  Warning
3       1  2026-06-10T06:06:12.615Z  10.10.10.65         4.22  Warning
4       1  2026-06-10T06:01:13.485Z  10.10.10.65         3.77  Warning

CPU2

   hostId                 timestamp      hostName  cpuUsagePct  status
0       2  2026-06-10T06:20:04.701Z  10.10.10.150         2.32  Normal
1       2  2026-06-10T06:15:15.846Z  10.10.10.150         2.84  Normal
2       2  2026-06-10T06:11:04.920Z  10.10.10.150         2.06  Normal
3       2  2026-06-10T06:06:12.615Z  10.10.10.150         2.16  Normal
4       2  2026-06-10T06:01:13.485Z  10.10.10.150         2.52  Normal

CPU3

   hostId                 timestamp    hostName  cpuUsagePct  status
0       3  2026-06-10T06:20:04.701Z  10.10.10.2        27.29  Normal
1       3  2026-06-10T06:15:15.846Z  10.10.10.2        26.62  Normal
2       3  2026-06-10T06:11:04.920Z  10.10.10.2        28.81  Normal
3       3  2026-06-10T06:06:12.615Z  10.10.10.2        28.62  Normal
4       3  2026-06-10T06:01:13.485Z  10.10.10.2        28.61  Normal

In [7]:
# Check column names
print(cpu1.columns)
print(cpu2.columns)
print(cpu3.columns)

Index(['hostId', 'timestamp', 'hostName', 'cpuUsagePct', 'status'], dtype='object')
Index(['hostId', 'timestamp', 'hostName', 'cpuUsagePct', 'status'], dtype='object')
Index(['hostId', 'timestamp', 'hostName', 'cpuUsagePct', 'status'], dtype='object')

In [ ]:
# convert timestamp columns
cpu1["timestamp"] = pd.to_datetime(cpu1["timestamp"])
cpu2["timestamp"] = pd.to_datetime(cpu2["timestamp"])
cpu3["timestamp"] = pd.to_datetime(cpu3["timestamp"])

In [9]:
# verify dataset size
print(cpu1.shape)
print(cpu2.shape)
print(cpu3.shape)

print("\nTotal rows expected:")
print(len(cpu1) + len(cpu2) + len(cpu3))

(500, 5)
(500, 5)
(500, 5)

Total rows expected:
1500

In [10]:
# combining all CPU Datasets
cpu_master = pd.concat(
    [cpu1, cpu2, cpu3],
    ignore_index=True
)
cpu_master.shape

(1500, 5)

In [11]:
# inspect combined dataset
cpu_master.head()
# verify unique hosts
cpu_master["hostName"].unique()

array(['10.10.10.65', '10.10.10.150', '10.10.10.2'], dtype=object)

In [12]:
# CPU Dataset information
cpu_master.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   hostId       1500 non-null   int64
 1   timestamp    1500 non-null   datetime64[ns, UTC]
 2   hostName     1500 non-null   object
 3   cpuUsagePct  1500 non-null   float64
 4   status       1500 non-null   object
dtypes: datetime64[ns, UTC](1), float64(1), int64(1), object(2)
memory usage: 58.7+ KB

In [13]:
# missing values check
cpu_master.isnull().sum()

hostId         0
timestamp      0
hostName       0
cpuUsagePct    0
status         0
dtype: int64

In [14]:
# duplicate check
cpu_master.duplicated().sum()

np.int64(0)

In [15]:
# timestamp range
print("Earliest Timestamp:")
print(cpu_master["timestamp"].min())

print("\nLatest Timestamp:")
print(cpu_master["timestamp"].max())

Earliest Timestamp:
2026-06-08 12:46:13.776000+00:00

Latest Timestamp:
2026-06-10 06:20:04.701000+00:00

In [16]:
# Sort dataset
cpu_master = cpu_master.sort_values(
    ["hostName", "timestamp"]
)

In [17]:
# reset index
cpu_master = cpu_master.reset_index(
    drop=True
)

In [18]:
# save processed dataset
Path("../data/Processed").mkdir(
    parents=True,
    exist_ok=True
)
cpu_master.to_csv(
    "../data/Processed/cpu_master.csv",
    index=False
)

In [19]:
print(cpu_master.shape)

cpu_master.head()

(1500, 5)

   hostId                        timestamp      hostName  cpuUsagePct  status
0       2 2026-06-08 12:46:13.776000+00:00  10.10.10.150         1.97  Normal
1       2 2026-06-08 12:51:15.113000+00:00  10.10.10.150         1.81  Normal
2       2 2026-06-08 12:56:12.448000+00:00  10.10.10.150         3.39  Normal
3       2 2026-06-08 13:01:12.997000+00:00  10.10.10.150         1.92  Normal
4       2 2026-06-08 13:06:13.341000+00:00  10.10.10.150         5.37  Normal